name: Release
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
env:
  IMG: ghcr.io/${{github.repository}}
jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: refs/tags/${{ inputs.tag }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create image tags
        id: tags
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMG }}
          tags: |
            type=sha,enable=false
            type=semver,pattern={{version}},value=${{ inputs.tag }}
            type=semver,pattern={{major}}.{{minor}},value=${{ inputs.tag }}
      - name: Build & push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            gh_token=${{ secrets.GITHUB_TOKEN }}
          tags: ${{ steps.tags.outputs.tags }}
          cache-from: type=registry,ref=${{ env.IMG }}:buildcache
          cache-to: type=registry,ref=${{ env.IMG }}:buildcache,mode=max
