name: Prerelease
on: push
jobs:
  increment:
    permissions: write-all
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout step
      uses: actions/checkout@v4

    - name: Update version
      run: |
        ${{ vars.version_patch = $vars.version_patch + 1}}